### ISSUE TITLE
To-Do Lists

### ISSUE THREAD

**Issue by JeonDohyeon** [JeonDohyeon/imitated-seed#10]
## 렌더러 오류 수정
- [ ] 삼중괄호 문제 해결 gdl-blue#14
- [ ] 토론 댓글 문제 해결하기 gdl-blue#23
- [ ] 주석 파싱 고치기 gdl-blue#31
- [ ] 

## 렌더러 기능 추가
- [ ] 다크 모드 지원

## 나무위키 전용 기능
- [ ] gdl-blue#29

## 코드 가독성 해결
- [ ] dohyeon-ghworkspace#1 

## 기타 기능
- [ ] 파일 서버 추가 gdl-blue#15
- [ ] 이메일 인증 기능 gdl-blue#22
